- hosts: all
  vars:
    nodejs_version: "v7.9.0"
    mysql_password: "password"
  become: yes
  become_user: root
  roles:
    - role: common
    - role: mysql
    - role: nginx
    - role: golang
    - role: nodejs
    - role: portal

