- name: get application
  git:
    repo: "https://int-tt:0dfd5565bf4f60be9c67341b9b4762ff5f39e375@github.com/orisano/r-isucon"
    dest: /home/isucon/r-isucon

- name: algon2 install
  git:
    repo: https://github.com/P-H-C/phc-winner-argon2.git
    dest: /usr/argon2

- name: make install argon2
  make:
    chdir: /usr/argon2
    target: install

#sudo ln -s /usr/lib/libargon2.so.1 /lib64/
- name: create symbolic link
  file:
    src: "/usr/lib/libargon2.so.1"
    dest: "/lib64/libargon2.so.1"
    state: link

- name: migration sql
  shell: |
    mysql -u root -ppassword < /home/isucon/r-isucon/portal/init.sql

- name: deploy env.sh
  copy:
    src: "environment"
    dest: "/etc/environment"
    owner: "root"
    group: "root"
    mode: "0644"

- name: install yarn
  npm:
    name: yarn
    global: yes
- name: yarn sen ln
  alternatives:
    name: "{{ item }}"
    path: "/usr/local/nodejs/bin/{{ item }}"
    link: "/usr/bin/{{ item }}"
  with_items:
    - yarn

# - name: yarn install portal
#   shell: cd /home/isucon/r-isucon/portal && sudo yarn install
#   become: yes
#   become_user: isucon

# - name: yarn build portal
#   shell: cd /home/isucon/r-isucon/portal && sudo yarn build
#   become: yes
#   become_user: isucon

- name: deploy service file
  copy:
    src: "r-isucon-portal.service"
    dest: "/etc/systemd/system"
    owner: "root"
    group: "root"
    mode: "0644"

- name: change mode and owner for r-isucon
  file:
    path: "/home/isucon/r-isucon"
    owner: isucon
    group: isucon
    recurse: yes

- name: start r-sicuon-node
  systemd:
    daemon_reload: "yes"
    name: "{{ item }}"
    state: "started"
    enabled: "yes"
  with_items:
  # - "r-isucon-portal.service"
  - "nginx"