---

- name: golang binary install
  file:
    path: "/usr/go"
    state: directory
    recurse: yes
    mode: 0755

- name: downloag golang
  get_url:
    url: "https://dl.google.com/go/go1.10.linux-amd64.tar.gz"
    checksum: "sha256:b5a64335f1490277b585832d1f6c7f8c6c11206cba5cd3f771dcb87b98ad1a33"
    dest: "/tmp/go1.10.linux-amd64.tar.gz"

- name: unarchive a golang
  unarchive:
    src: "/tmp/go1.10.linux-amd64.tar.gz"
    dest: "/usr/"
    remote_src: True

- name: change mode and owner
  file:
    path: "/usr/go"
    owner: root
    group: root

- name: create symbolic link
  file:
    src: "/usr/go"
    dest: "/usr/local/go"
    state: link

- name: link
  alternatives:
    name: "go"
    path: "/usr/local/go/bin/go"
    link: "/usr/bin/go"
    
- name: go get -u dep
  shell: go get -u github.com/golang/dep/cmd/dep
  become: yes
  become_user: isucon

- name: change mode and owner for r-isucon
  file:
    path: "/home/isucon/go"
    owner: isucon
    group: isucon